name: CI-CD Pipeline
 
on:

  push:

    branches: [ main ]
 
jobs:

  Build:

    runs-on: self-hosted
 
    steps:

      - name: Checkout Code

        uses: actions/checkout@v4
 
      - name: Build

        run: echo "Build success"
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test
        run: echo "Tests passed"
  Deploy:
    needs: Test
    runs-on: self-hosted
    steps:
      - name: checkout Code
        uses: actions/checkout@v4
      - name: Deploy (CD)
        shell: powershell
        run: |
          wsl -d Ubuntu -- python3 /mnt/c/Devops_training/DevOpsCICDProject/actions-runner2/_work/DevOpsCICDProject/DevOpsCICDProject/app2.py
